[package]
name = "pmv"
description = "Pattern based mv(1)"
version = "0.4.1"
authors = ["Suguru Yamamoto <sgryjp@gmail.com>"]
repository = "https://github.com/sgryjp/pmv"
readme = "README.md"
license = "MIT"
categories = ["command-line-utilities", "filesystem"]
edition = "2018"

[dependencies]
ansi_term = "~0.12.1"
atty = "~0.2"

[dependencies.clap]
version = "3.2.5"
features = ["cargo", "color", "wrap_help"]

[dev-dependencies]
function_name = "0.2.0"
