[package]
name = "pmv"
description = "Pattern based mv(1)"
version = "0.1.1"
authors = ["Suguru Yamamoto <sgryjp@gmail.com>"]
homepage = "https://github.com/sgryjp/pmv"
readme = "README.md"
license = "MIT"
categories = ["command-line-utilities", "filesystem"]
edition = "2018"

[dependencies]
ansi_term = "~0.12.1"
atty = "~0.2"

[dependencies.clap]
version = "~2.33.0"
features = [ "color", "wrap_help" ]
