name: CI

on:
  push:
    branches:
      - master
      - ci
  pull_request:
    branches: master

jobs:
  ci:
    strategy:
      matrix:
        target:
          - i686-pc-windows-gnu
          - i686-pc-windows-msvc
          - i686-unknown-linux-gnu
          - i686-unknown-linux-musl
          - x86_64-pc-windows-gnu
          - x86_64-pc-windows-msvc
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
        include:
          - target: i686-pc-windows-gnu
            os: windows-latest
          - target: i686-pc-windows-msvc
            os: windows-latest
          - target: i686-unknown-linux-gnu
            os: ubuntu-latest
          - target: i686-unknown-linux-musl
            os: ubuntu-latest
          - target: x86_64-pc-windows-gnu
            os: windows-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Rust target
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}

    - name: Build program
      run: cargo build --verbose --release --target=${{ matrix.target }}

    - name: Run tests
      run: cargo test --verbose --target=${{ matrix.target }}
      env:
        RUST_BACKTRACE: 1
