name: CI

on:
  push:
    branches:
      - master
      - ci
  pull_request:
    branches: master

jobs:
  ci:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        include:
          os: ubuntu-latest
          target:
            - i686-unknown-linux-gnu
            - i686-unknown-linux-musl
            - x86_64-unknown-linux-gnu
            - x86_64-unknown-linux-musl
        include:
          os: windows-latest
          target:
            - i686-pc-windows-gnu
            - i686-pc-windows-musl
            - x86_64-pc-windows-gnu
            - x86_64-pc-windows-musl
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Rust target
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}

    - name: Build program
      run: cargo build --verbose --release --target=${{ matrix.target }}

    - name: Run tests
      run: cargo test --verbose --target=${{ matrix.target }}
      env:
        RUST_BACKTRACE: 1
