name: linux-build

on:
  push:
    branches:
      - master
      - ci
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: ${{ github.ref }}
    - name: Build
      run: cargo build --verbose --release
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: ${{ github.ref }}
    - name: Run tests
      run: cargo test --verbose
      env:
        RUST_BACKTRACE: 1
