name: linux-build

on:
  push:
    branches:
      - master
      - ci
  pull_request:
    branches: master

jobs:
  strategy:
    matrix:
      target:
        - i686-unknown-linux-gnu
        - i686-unknown-linux-musl
        - x86_64-unknown-linux-gnu
        - x86_64-unknown-linux-musl
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
      with:
        ref: ${{ github.ref }}
    - name: Build program
      run: cargo build --verbose --release --target=${{ matrix.target }}
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
      with:
        ref: ${{ github.ref }}
    - name: Run tests
      run: cargo test --verbose --target=${{ matrix.target }}
      env:
        RUST_BACKTRACE: 1
